### ISSUE TITLE
Error while daily Cronjob

### ISSUE THREAD

**Issue by DAThosting** [0100Dev/WHMCS-Mollie#60] opened 2020-01-08 08:26 UTC
I get this error in every daily cron.
My cron can't run through cause of this error.

`[WHMCS Application] ERROR: TypeError: Argument 1 passed to GuzzleHttp\Ring\Client\StreamHandler::__invoke() must be of the type array, object given, called in /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php on line 277 and defined in /path/to/whmcs/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26 Stack trace: #0 /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\Ring\Client\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #1 /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #2 /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array) #3 /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', 'https://pki.whm...', Array) #4 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): GuzzleHttp\Client->__call('get', Array) #5 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getUrl('https://pki.whm...') #6 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getPathFromKeyserver('certs.json') #7 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getCertMetadata() #8 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->reloadCrls() #9 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getCrlForCertificate(Object(WHMCS\Installer\Composer\Certificate)) #10 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->validateCertificateNotRevoked(Object(WHMCS\Installer\Composer\Certificate)) #11 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getTrustedCertificate('515FCBEB9958DA4...', 2) #12 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->validateCertificateSignatureIsTrusted(Object(WHMCS\Installer\Composer\Certificate)) #13 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getTrustedCertificate('0C12A820D7DD9ED...', 1) #14 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/PackagesFile.php(0): WHMCS\Installer\Composer\CertificateManager->getValidCodeSigningCertificateContent('0C12A820D7DD9ED...') #15 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/WhmcsRepository.php(0): WHMCS\Installer\Composer\PackagesFile->validateNotificationSignatures(Array) #16 /path/to/whmcs/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(462): WHMCS\Installer\Composer\WhmcsRepository->fetchFile('https://release...', 'UpdatePackagesD...') #17 /path/to/whmcs/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(256): Composer\Repository\ComposerRepository->loadRootServerFile() #18 /path/to/whmcs/vendor/composer/composer/src/Composer/DependencyResolver/Pool.php(99): Composer\Repository\ComposerRepository->hasProviders() #19 /path/to/whmcs/vendor/composer/composer/src/Composer/Installer.php(402): Composer\DependencyResolver\Pool->addRepository(Object(WHMCS\Installer\Composer\WhmcsRepository), Array) #20 /path/to/whmcs/vendor/composer/composer/src/Composer/Installer.php(228): Composer\Installer->doInstall(Object(Composer\Repository\InstalledArrayRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array, false) #21 /path/to/whmcs/vendor/composer/composer/src/Composer/Command/UpdateCommand.php(173): Composer\Installer->run() #22 /path/to/whmcs/vendor/symfony/console/Command/Command.php(259): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #23 /path/to/whmcs/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #24 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/WhmcsComposerApplication.php(0): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #25 /path/to/whmcs/vendor/symfony/console/Application.php(192): WHMCS\Installer\Composer\WhmcsComposerApplication->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #26 /path/to/whmcs/vendor/composer/composer/src/Composer/Console/Application.php(189): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #27 /path/to/whmcs/vendor/symfony/console/Application.php(123): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #28 /path/to/whmcs/vendor/composer/composer/src/Composer/Console/Application.php(99): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #29 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerWrapper.php(0): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(WHMCS\Installer\Composer\MonologBufferedOutputWrapper)) #30 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerWrapper.php(0): WHMCS\Installer\Composer\ComposerWrapper->update() #31 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerWrapper->getLatestVersion() #32 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerUpdate->WHMCS\Installer\Composer\{closure}() #33 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/ComposerUpdate.php(0): WHMCS\Installer\Composer\ComposerUpdate->doComposerCommand(Object(Closure)) #34 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Installer/Update/Updater.php(0): WHMCS\Installer\Composer\ComposerUpdate->getLatestVersion(true) #35 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Task/CheckForWhmcsUpdate.php(0): WHMCS\Installer\Update\Updater->fetchComposerLatestVersion() #36 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\CheckForWhmcsUpdate->__invoke() #37 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #38 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #39 /path/to/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) #40 /path/to/whmcs/vendor/symfony/console/Command/Command.php(259): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 /path/to/whmcs/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 /path/to/whmcs/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 /path/to/whmcs/vendor/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 /var/www/vhosts/private.subscription/whmcssecuredata/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #45 {main} {"exception":"[object] (TypeError(code: 0): Argument 1 passed to GuzzleHttp\\Ring\\Client\\StreamHandler::__invoke() must be of the type array, object given, called in /path/to/whmcs/modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php on line 277 at /path/to/whmcs/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26)"}`

WHMCS: 7.8.3
PHP: 7.3.13

**Comment by Wouter0100** [comment] 2020-01-08 23:43
Duplicate of #57

**Closed by Wouter0100** 2020-01-08 23:43 UTC
